// <auto-generated />
namespace GestionProductosMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class anotaciones24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(anotaciones24));
        
        string IMigrationMetadata.Id
        {
            get { return "201812030008462_anotaciones24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
